# -*- coding: utf-8 -*-
import os
import sys
import glob
import time
import random
import shutil
import logging
import json
import argparse
import csv
import numpy as np

# Add project root and src to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src")))
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FORMAL_D04_MODE = "D04_AppGeoPhys1000"

# Avoid OpenMP duplicate initialization crashes on some Windows environments.
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from collections import defaultdict
from sklearn.metrics import recall_score, precision_score, f1_score

try:
    from src.models.model_dgcnn import DGCNN
    from src.models.model_pointnet2 import PointNet2
    from src.models.pointnet import PointNet
    from src.models.model_pointmlp import PointMLP
    from src.models.model_point_transformer_formal import PointTransformerSeg
    from src.models.model_pointnext_official import PointNeXt
    from src.models.model_curvenet_formal import CurveNetSeg
except ImportError as e:
    print(f"Warning: Standard models in src/models/ not found. Error: {e}")

# ============================================
# ============================================
class Config:
    MODE = FORMAL_D04_MODE
    RUN_MODEL_TAG = None
    RUN_TAG = None
    
    # Run candidate-level segmentation training and full-space evaluation.
    RUN_STAGE = 2
    
    # Experiment directory naming.
    EXP_NAME = f"ablation_{MODE}"
    
    # LCC candidate-data root generated by 02_generate_lcc_candidates.py.
    STAGE2_OFFLINE_ROOT = os.path.join(PROJECT_ROOT, "outputs", "LCC_Offline_Data")

    # Offline data path for the current mode.
    STAGE2_OFFLINE_DIR = os.path.join(STAGE2_OFFLINE_ROOT, MODE)
  
    # Output path for the current experiment.
    RESULTS_ROOT = os.path.join(PROJECT_ROOT, "experiments", "formal_baseline_results")
    OUTPUT_ROOT = os.path.join(RESULTS_ROOT, EXP_NAME)
    
    MODEL_SAVE_DIR = os.path.join(OUTPUT_ROOT, "checkpoints")
    VIZ_DIR = os.path.join(OUTPUT_ROOT, "visualizations")
    LOG_DIR = os.path.join(OUTPUT_ROOT, "logs")
    LOG_FILE = os.path.join(LOG_DIR, f"{EXP_NAME}_stage2_train.log")
    
    @classmethod
    def update_mode(cls, new_mode):
        """Update mode-specific paths and experiment names."""
        cls.MODE = new_mode
        exp_parts = ["ablation", new_mode]
        if cls.RUN_MODEL_TAG is not None:
            exp_parts.append(cls.RUN_MODEL_TAG)
        if cls.RUN_TAG is not None:
            exp_parts.append(cls.RUN_TAG)
        cls.EXP_NAME = "_".join(exp_parts)
        cls.STAGE2_OFFLINE_DIR = os.path.join(cls.STAGE2_OFFLINE_ROOT, new_mode)
        # Single-model formal runs are stored beside the retained
        # checkpoints as <results-root>/<model>/.
        if cls.RUN_MODEL_TAG is not None:
            cls.OUTPUT_ROOT = os.path.join(cls.RESULTS_ROOT, cls.RUN_MODEL_TAG)
        else:
            cls.OUTPUT_ROOT = os.path.join(cls.RESULTS_ROOT, cls.EXP_NAME)
        cls.MODEL_SAVE_DIR = os.path.join(cls.OUTPUT_ROOT, "checkpoints")
        cls.VIZ_DIR = os.path.join(cls.OUTPUT_ROOT, "visualizations")
        cls.LOG_DIR = os.path.join(cls.OUTPUT_ROOT, "logs")
        cls.LOG_FILE = os.path.join(cls.LOG_DIR, f"{cls.EXP_NAME}_stage2_train.log")
    
    # Reproducibility and runtime settings.
    SEED = 42
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    NUM_WORKERS = 4
    
    # Candidate-level XYZRGB input with full-space evaluation.
    STAGE2_MODEL_TYPES = [
        'pointnet', 'pointnet2', 'pointmlp', 'dgcnn', 'pointtransformer',
        'pointnext', 'curvenet',
    ]
    STAGE2_EPOCHS = 100
    STAGE2_BATCH_SIZE = 8
    # All comparison models use the same physical batch size.
    STAGE2_MODEL_BATCH_SIZE_OVERRIDES = {}
    # Full-candidate validation can contain tens of thousands of LCC candidates.
    # Every baseline therefore uses the same deterministic 4096-candidate
    # evaluation chunks. This covers every retained candidate, matches the
    # training input budget, and prevents model-specific inference support.
    DGCNN_EVAL_STRATEGY = "chunked"
    DGCNN_EVAL_CHUNK_POINTS = 4096
    STAGE2_PATIENCE = 15
    STAGE2_EVAL_EVERY = 1
    STAGE2_SAMPLE_POINTS = 4096
    STAGE2_INPUT_CHANNELS = 6 # [XYZ(3), RGB(3)]
    STAGE2_USE_ONLINE_AUGMENT = True
    STAGE2_SPLIT_POLICY = "synthetic_style_holdout"
    STAGE2_HOLDOUT_STYLES = ("TeBu", "XBL")
    STAGE2_OPTIMIZER = "adam"
    DEFER_REAL_EVALUATION = False
    
    STAGE2_AUG_MODE = 'none' 
    
    # Stage 2 baseline training protocol. All backbones use the same loss
    # weighting so the ablation focuses on dataset variants, not model-specific
    # regularization choices.
    STAGE2_MODEL_CONFIGS = {
        'pointnet': {'lr': 5e-4,     'pos_weight': 2.0,       'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   },
        'dgcnn': {'lr': 5e-4,       'pos_weight': 2.0,        'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   },
        'pointnet2': {'lr': 5e-4,    'pos_weight': 2.0,       'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   },
        'pointmlp': {    'lr': 5e-4,  'pos_weight': 2.0,      'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   },
        'pointtransformer': {'lr': 5e-4, 'pos_weight': 2.0,   'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   },
        'pointnext': {'lr': 5e-4, 'pos_weight': 2.0,          'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   },
        'curvenet': {'lr': 5e-4, 'pos_weight': 2.0,           'weight_decay': 1e-4,     'use_smooth_loss': False,  'smooth_weight': 0.0   }
    }

# Set random seed for reproducibility.
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(Config.SEED)

def seed_worker(worker_id):
    worker_seed = Config.SEED + worker_id
    random.seed(worker_seed)
    np.random.seed(worker_seed)
    torch.manual_seed(worker_seed)

def make_loader(dataset, batch_size, shuffle, num_workers=None):
    if num_workers is None:
        num_workers = Config.NUM_WORKERS
    generator = torch.Generator()
    generator.manual_seed(Config.SEED)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=True,
        persistent_workers=num_workers > 0,
        worker_init_fn=seed_worker,
        generator=generator,
    )

def parse_args():
    parser = argparse.ArgumentParser(description="Run the paper's D04-1000 source-only backbone comparison.")
    parser.add_argument(
        "--mode",
        default=Config.MODE,
        choices=[FORMAL_D04_MODE],
        help="Locked paper protocol; only D04_AppGeoPhys1000 is accepted.",
    )
    parser.add_argument(
        "--model",
        default=None,
        choices=[
            "pointnet", "pointnet2", "pointmlp", "dgcnn", "pointtransformer",
            "pointnext", "curvenet", "all",
        ],
        help="Backbone to run. The default runs all source-only baselines.",
    )
    parser.add_argument("--run-tag", default="paper_protocol", help="Optional output suffix.")
    parser.add_argument(
        "--offline-root",
        default=Config.STAGE2_OFFLINE_ROOT,
        help="Root containing D04_AppGeoPhys1000, shoe_a, shoe_b, and shoe_c candidate directories.",
    )
    parser.add_argument(
        "--results-root",
        default=Config.RESULTS_ROOT,
        help="Directory in which run-specific result folders are created.",
    )
    parser.add_argument("--num-workers", type=int, default=None, help="Override DataLoader workers.")
    parser.add_argument(
        "--optimizer",
        choices=("adam", "adamw"),
        default=Config.STAGE2_OPTIMIZER,
        help="Optimizer used by the isolated formal run (default preserves the historical Adam protocol).",
    )
    parser.add_argument(
        "--defer-real-evaluation",
        action="store_true",
        help=(
            "Do not inspect the real test split in the training process. "
            "Use the post-training evaluator to select a threshold on synthetic validation first."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate the locked protocol and instantiate the requested model without training.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace an existing run directory. Without this flag, existing results are protected.",
    )
    return parser.parse_args()

class Stage2Dataset(Dataset):
    """Dataset wrapper for Stage-2 ablation caches."""
    @staticmethod
    def _style_name(file_path):
        stem = os.path.splitext(os.path.basename(str(file_path)))[0]
        if "-" not in stem:
            return stem
        return stem.split("-", 1)[0]

    def __init__(self, offline_dir, split="train", augment=False):
        self.offline_dir = offline_dir
        self.split = split
        self.augment = augment 
        self.empty_candidate_count = 0
        self.empty_candidate_policy = "none"
        self.split_policy = Config.STAGE2_SPLIT_POLICY
        self.holdout_styles = tuple(Config.STAGE2_HOLDOUT_STYLES)
        
        sim_train_path = offline_dir
        self.sim_files = sorted(glob.glob(os.path.join(sim_train_path, "*.npz")) + glob.glob(os.path.join(sim_train_path, "*.npy")))
        self.synthetic_val_files = [
            f for f in self.sim_files
            if self._style_name(f) in set(self.holdout_styles)
        ]
        self.synthetic_train_files = [
            f for f in self.sim_files
            if self._style_name(f) not in set(self.holdout_styles)
        ]
        
        eval_pool = []
        real_entities = ['shoe_a', 'shoe_b', 'shoe_c']
        for ent in real_entities:
            path = os.path.join(Config.STAGE2_OFFLINE_ROOT, ent)
            eval_pool.extend(sorted(glob.glob(os.path.join(path, "*.npz")) + glob.glob(os.path.join(path, "*.npy"))))
        
        eval_pool.sort()
        self.real_val_files = []
        self.real_test_files = eval_pool

        if split == "train":
            # Formal ablation training uses pure synthetic data only.
            train_files = self.synthetic_train_files
            self.file_list, empty_count = self._filter_empty_candidates(train_files)
            self.empty_candidate_count = empty_count
            self.empty_candidate_policy = "skip_for_training"
            print(f"[Stage2Dataset] Train Split (Pure Sim): {len(self.file_list)} files from {sim_train_path}")
            if empty_count:
                print(f"[Stage2Dataset] Filtered {empty_count} empty-candidate training files.")
        elif split == "val":
            self.file_list, empty_count = self._filter_empty_candidates(self.synthetic_val_files)
            self.empty_candidate_count = empty_count
            self.empty_candidate_policy = "skip_empty_synthetic_validation_candidates"
            print(f"[Stage2Dataset] Val Split (Pure Sim holdout {self.holdout_styles}): {len(self.file_list)} files")
            if empty_count:
                print(f"[Stage2Dataset] Filtered {empty_count} empty-candidate validation files.")
        else: # test
            self.file_list = self.real_test_files
            self.empty_candidate_policy = "all_background_for_full_space_evaluation"
            print(f"[Stage2Dataset] Test Split (Pure Real all scans): {len(self.file_list)} files")
        
        if len(self.file_list) == 0:
             print(f"Warning: No data found for {split} in {offline_dir}. Check LCC offline data.")
             
    def __len__(self):
        return len(self.file_list)

    def _empty_metadata(self):
        return {
            "has_full_space": torch.tensor(False),
            "orig_index": torch.empty(0, dtype=torch.long),
            "raw_label": torch.empty(0, dtype=torch.long),
            "raw_num_points": torch.tensor(0, dtype=torch.long),
            "file_path": "",
        }

    def _candidate_count(self, file_path):
        loaded = np.load(file_path, allow_pickle=False)
        try:
            if isinstance(loaded, np.lib.npyio.NpzFile):
                if "candidate_points" in loaded.files:
                    return int(len(loaded["candidate_points"]))
                if "label" in loaded.files:
                    return int(len(loaded["label"]))
                return int(len(loaded["features"]))
            return int(len(loaded))
        finally:
            if isinstance(loaded, np.lib.npyio.NpzFile):
                loaded.close()

    def _filter_empty_candidates(self, files):
        kept = []
        empty = 0
        for file_path in files:
            try:
                if self._candidate_count(file_path) > 0:
                    kept.append(file_path)
                else:
                    empty += 1
            except Exception as exc:
                print(f"Warning: failed to inspect candidate file {file_path}: {exc}")
                empty += 1
        return kept, empty

    def summary(self):
        return {
            "split": self.split,
            "offline_dir": self.offline_dir,
            "split_policy": self.split_policy,
            "holdout_styles": list(self.holdout_styles),
            "files_used": len(self.file_list),
            "empty_candidate_count": int(self.empty_candidate_count),
            "empty_candidate_policy": self.empty_candidate_policy,
        }

    def _load_offline_features(self, file_path):
        loaded = np.load(file_path, allow_pickle=False)
        if isinstance(loaded, np.lib.npyio.NpzFile):
            data = loaded["features"].astype(np.float32)
            metadata = self._empty_metadata()
            if {"orig_index", "raw_label", "raw_num_points"}.issubset(set(loaded.files)):
                metadata = {
                    "has_full_space": torch.tensor(True),
                    "orig_index": torch.from_numpy(loaded["orig_index"].astype(np.int64)),
                    "raw_label": torch.from_numpy(loaded["raw_label"].astype(np.int64)),
                    "raw_num_points": torch.tensor(int(loaded["raw_num_points"]), dtype=torch.long),
                    "file_path": str(file_path),
                }
            loaded.close()
            return data, metadata
        return loaded.astype(np.float32), self._empty_metadata()

    def _sample_rows(self, data, file_path):
        target_n = int(getattr(Config, "STAGE2_SAMPLE_POINTS", 8192))
        if len(data) == target_n:
            return data
        replace = len(data) < target_n
        if self.split == "train":
            indices = np.random.choice(len(data), target_n, replace=replace)
        else:
            seed = sum(bytearray(str(file_path).encode("utf-8"))) % (2**32 - 1)
            rng = np.random.default_rng(seed)
            indices = rng.choice(len(data), target_n, replace=replace)
        return data[indices]

    def _augment(self, feat):
        """Apply the configured online augmentation mode."""
        mode = Config.STAGE2_AUG_MODE
        if mode == 'none':
            return feat

        # feat: (C, N)
        xyz = feat[:3, :]
        rgb = feat[3:6, :]
        
        # Enable mirror augmentation for mirror/full modes.
        if mode in ['mirror', 'full']:
            if np.random.rand() > 0.5:
                xyz[1, :] = -xyz[1, :]
                if feat.shape[0] >= 13:
                    feat[11, :] = -feat[11, :]

        angle = np.random.uniform(0, 2 * np.pi)
        rot_matrix = np.array([
            [np.cos(angle), -np.sin(angle), 0],
            [np.sin(angle),  np.cos(angle), 0],
            [0, 0, 1]
        ])
        xyz = np.dot(rot_matrix, xyz)
        # Rotate normals consistently with XYZ when normal channels are present.
        if feat.shape[0] >= 13:
            normal = feat[10:13, :]
            normal = np.dot(rot_matrix, normal)
            feat[10:13, :] = normal

        s = np.random.uniform(0.9, 1.1)
        xyz = xyz * s

        xyz += np.random.normal(0, 0.005, size=xyz.shape)

        # Color brightness augmentation.
        a = np.random.uniform(0.8, 1.2)
        rgb = np.clip(rgb * a, 0.0, 1.0)
        if feat.shape[0] >= 10:
            feat[7:10, :] = feat[7:10, :] * (a**2)

        # Recompute theta only when the full augmentation protocol is enabled.
        if mode == 'full' and feat.shape[0] > 6:
            new_center = np.mean(xyz, axis=1, keepdims=True)
            rel_xyz = xyz - new_center
            new_theta = np.arctan2(rel_xyz[1, :], rel_xyz[0, :]) / np.pi
            feat[6, :] = new_theta

        # Write augmented features back.
        feat[:3, :] = xyz
        feat[3:6, :] = rgb
        return feat

    def __getitem__(self, idx):
        file_path = self.file_list[idx]
        data, metadata = self._load_offline_features(file_path)
        if self.split == "train":
            data = self._sample_rows(data, file_path)
            metadata = self._empty_metadata()
        elif len(data) == 0:
            data = np.zeros((1, Config.STAGE2_INPUT_CHANNELS + 1), dtype=np.float32)
        
        # The LCC cache can store extra descriptors for auditing, while the
        # Benchmark input is restricted to XYZRGB for all backbones.
        if data.shape[1] >= Config.STAGE2_INPUT_CHANNELS + 1:
            feat = data[:, :Config.STAGE2_INPUT_CHANNELS].T
            label = data[:, -1].astype(np.int64)
        else:
            raise ValueError(
                f"Ablation pipeline requires at least {Config.STAGE2_INPUT_CHANNELS + 1} columns "
                f"(XYZRGB + label), but got {data.shape[1]}. Path: {file_path}"
            )
        
        if self.augment:
            feat = self._augment(feat)
        
        return torch.from_numpy(feat).float(), torch.from_numpy(label).long(), metadata


def validate_formal_protocol(config, train_ds, val_ds, test_ds):
    """Fail before training if a paper-critical setting has drifted."""
    expected = {
        "mode": FORMAL_D04_MODE,
        "epochs": 100,
        "batch_size": 8,
        "patience": 15,
        "sample_points": 4096,
        "input_channels": 6,
        "split_policy": "synthetic_style_holdout",
        "holdout_styles": ("TeBu", "XBL"),
        "augmentation": "none",
        "dgcnn_eval_chunk_points": 4096,
        "train_files": 800,
        "validation_files": 200,
        "real_test_files": 67,
        "optimizer": config.STAGE2_OPTIMIZER,
    }
    observed = {
        "mode": config.MODE,
        "epochs": config.STAGE2_EPOCHS,
        "batch_size": config.STAGE2_BATCH_SIZE,
        "patience": config.STAGE2_PATIENCE,
        "sample_points": config.STAGE2_SAMPLE_POINTS,
        "input_channels": config.STAGE2_INPUT_CHANNELS,
        "split_policy": config.STAGE2_SPLIT_POLICY,
        "holdout_styles": tuple(config.STAGE2_HOLDOUT_STYLES),
        "augmentation": config.STAGE2_AUG_MODE,
        "dgcnn_eval_chunk_points": config.DGCNN_EVAL_CHUNK_POINTS,
        "train_files": len(train_ds),
        "validation_files": len(val_ds),
        "real_test_files": len(test_ds),
        "optimizer": config.STAGE2_OPTIMIZER,
    }
    mismatches = {
        key: {"expected": expected[key], "observed": observed[key]}
        for key in expected
        if observed[key] != expected[key]
    }
    if config.STAGE2_MODEL_BATCH_SIZE_OVERRIDES:
        mismatches["model_batch_size_overrides"] = {
            "expected": {},
            "observed": config.STAGE2_MODEL_BATCH_SIZE_OVERRIDES,
        }
    for model_name in (
        "pointnet", "pointnet2", "pointmlp", "dgcnn", "pointtransformer",
        "pointnext", "curvenet",
    ):
        model_cfg = config.STAGE2_MODEL_CONFIGS[model_name]
        if float(model_cfg["lr"]) != 5e-4:
            mismatches[f"{model_name}_learning_rate"] = {
                "expected": 5e-4,
                "observed": model_cfg["lr"],
            }
        if float(model_cfg["weight_decay"]) != 1e-4:
            mismatches[f"{model_name}_weight_decay"] = {
                "expected": 1e-4,
                "observed": model_cfg["weight_decay"],
            }
    if str(config.STAGE2_OPTIMIZER).lower() not in {"adam", "adamw"}:
        mismatches["optimizer"] = {
            "expected": "adam or adamw",
            "observed": config.STAGE2_OPTIMIZER,
        }
    if mismatches:
        raise RuntimeError(
            "Formal D04-1000 protocol check failed:\n"
            + json.dumps(mismatches, indent=2)
        )

    if set(train_ds.file_list) & set(val_ds.file_list):
        raise RuntimeError("Synthetic training and validation files overlap.")
    if set(train_ds.file_list) & set(test_ds.file_list) or set(val_ds.file_list) & set(test_ds.file_list):
        raise RuntimeError("Real final-test files overlap a synthetic model-selection split.")
    print(">>> Formal protocol check passed: 800/200/67, batch 8, 4096 points, 100 epochs, patience 15.")


class DiceLoss(nn.Module):
    """Dice loss for the foreground class."""
    def __init__(self, smooth=1e-6):
        super(DiceLoss, self).__init__()
        self.smooth = smooth

    def forward(self, logits, target):
        # logits: (B, 2, N), target: (B, N)
        probs = F.softmax(logits, dim=1)[:, 1, :] # (B, N)
        target = target.float()
        
        intersection = (probs * target).sum(dim=1)
        union = probs.sum(dim=1) + target.sum(dim=1)
        
        dice = (2. * intersection + self.smooth) / (union + self.smooth)
        return 1 - dice.mean()

class ColorAwareSmoothnessLoss(nn.Module):
    """Optional color-aware smoothness regularizer."""
    def __init__(self, k=16):
        super(ColorAwareSmoothnessLoss, self).__init__()
        self.k = k

    def forward(self, logits, xyz, rgb):
        # logits: (B, 2, N), xyz: (B, 3, N), rgb: (B, 3, N)
        batch_size, _, num_points = xyz.size()
        
        # Spatial KNN distances.
        dist = -2 * torch.matmul(xyz.transpose(2, 1), xyz)
        xx = torch.sum(xyz**2, dim=1, keepdim=True)
        dist = xx + dist + xx.transpose(2, 1)
        idx = dist.topk(k=self.k, dim=-1, largest=False)[1] # (B, N, K)
        
        # Prediction probabilities.
        probs = F.softmax(logits, dim=1) # (B, 2, N)
        
        # Gather neighbor features by KNN indices.
        def gather_neighbors(feat, idx):
            B, C, N = feat.size()
            K = idx.size(2)
            idx_base = torch.arange(0, B, device=feat.device).view(-1, 1, 1) * N
            idx_flat = (idx + idx_base).view(-1)
            feat_t = feat.transpose(2, 1).contiguous()
            neighbor_feat = feat_t.view(B * N, C)[idx_flat, :]
            return neighbor_feat.view(B, N, K, C)

        neighbor_rgb = gather_neighbors(rgb, idx)      # (B, N, K, 3)
        neighbor_probs = gather_neighbors(probs, idx)  # (B, N, K, 2)
        
        center_rgb = rgb.transpose(2, 1).unsqueeze(2)      # (B, N, 1, 3)
        center_probs = probs.transpose(2, 1).unsqueeze(2)  # (B, N, 1, 2)
        
        # RGB distance between center and neighbor points.
        rgb_dist = torch.norm(center_rgb - neighbor_rgb, dim=-1) # (B, N, K)
        
        prob_diff = torch.abs(center_probs - neighbor_probs).sum(dim=-1) # (B, N, K)
        
        weight = torch.exp(-rgb_dist * 10.0)
        
        loss = (weight * prob_diff).mean()
        return loss

class Stage2Loss(nn.Module):
    """
    Combined imbalance-aware segmentation loss:
    weighted cross-entropy + Dice loss + optional smoothness regularization.
    """
    def __init__(self, pos_weight=2.0, use_smooth=True, smooth_weight=0.01):
        super(Stage2Loss, self).__init__()
        self.register_buffer('weight', torch.tensor([1.0, pos_weight]))
        self.ce = nn.CrossEntropyLoss(weight=self.weight)
        self.dice = DiceLoss()
        self.use_smooth = use_smooth
        self.smooth_weight = smooth_weight
        if use_smooth:
            self.smooth = ColorAwareSmoothnessLoss()

    def forward(self, logits, target, xyz, rgb):
        ce_loss = self.ce(logits, target)
        dice_loss = self.dice(logits, target)
        loss = ce_loss + dice_loss
        
        if self.use_smooth:
            smooth_loss = self.smooth(logits, xyz, rgb)
            loss += self.smooth_weight * smooth_loss
            
        return loss

class Stage2Trainer:
    """Trainer for Stage-2 fine segmentation ablation."""
    def __init__(self, config, current_model_type=None):
        self.cfg = config
        # Use the requested model type when provided.
        if current_model_type:
            self.model_type = current_model_type.lower()
        else:
            self.model_type = config.STAGE2_MODEL_TYPES[0].lower()
            
        self.m_cfg = config.STAGE2_MODEL_CONFIGS.get(self.model_type, config.STAGE2_MODEL_CONFIGS['dgcnn'])
        self.log_file = os.path.join(config.LOG_DIR, f"stage2_{self.model_type}_train.log")
        self.setup_logging()
        
        if self.model_type == 'dgcnn':
            self.model = DGCNN(num_classes=2, input_channels=config.STAGE2_INPUT_CHANNELS).to(config.DEVICE)
        elif self.model_type == 'pointnet2':
            self.model = PointNet2(num_classes=2, input_channels=config.STAGE2_INPUT_CHANNELS).to(config.DEVICE)
        elif self.model_type == 'pointnet':
            self.model = PointNet(num_classes=2, input_channels=config.STAGE2_INPUT_CHANNELS).to(config.DEVICE)
        elif self.model_type == 'pointmlp':
            self.model = PointMLP(num_classes=2, input_channels=config.STAGE2_INPUT_CHANNELS).to(config.DEVICE)
        elif self.model_type == 'pointtransformer':
            self.model = PointTransformerSeg(
                num_classes=2,
                input_channels=config.STAGE2_INPUT_CHANNELS,
            ).to(config.DEVICE)
        elif self.model_type == 'pointnext':
            self.model = PointNeXt(
                num_classes=2,
                input_channels=config.STAGE2_INPUT_CHANNELS,
            ).to(config.DEVICE)
        elif self.model_type == 'curvenet':
            self.model = CurveNetSeg(
                num_classes=2,
                input_channels=config.STAGE2_INPUT_CHANNELS,
            ).to(config.DEVICE)
        else:
            raise ValueError(f"Unknown Stage 2 model type: {self.model_type}")

        # Use the explicitly locked optimizer and common hyperparameters.
        optimizer_class = (
            optim.AdamW
            if str(config.STAGE2_OPTIMIZER).lower() == "adamw"
            else optim.Adam
        )
        self.optimizer = optimizer_class(
            self.model.parameters(),
            lr=self.m_cfg['lr'],
            weight_decay=self.m_cfg['weight_decay'],
        )
        # Cosine learning-rate schedule over the configured training horizon.
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=config.STAGE2_EPOCHS)
        
        self.criterion = Stage2Loss(
            pos_weight=self.m_cfg['pos_weight'],
            use_smooth=self.m_cfg['use_smooth_loss'],
            smooth_weight=self.m_cfg['smooth_weight']
        ).to(config.DEVICE)
        
        self.best_iou = -1.0
        self.history = defaultdict(list)

    def setup_logging(self):
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)
            
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s [%(levelname)s] %(message)s',
            handlers=[
                logging.FileHandler(self.log_file, mode="w", encoding="utf-8"),
                logging.StreamHandler()
            ]
        )
        self.logger = logging.getLogger(f"Stage2_{self.model_type}")

    def _eval_forward_once(self, feat, target):
        feat = feat.to(self.cfg.DEVICE, non_blocking=True)
        target = target.to(self.cfg.DEVICE, non_blocking=True)
        xyz, rgb = feat[:, :3, :], feat[:, 3:6, :]
        outputs = self.model(feat)
        logits = outputs[0] if isinstance(outputs, tuple) else outputs
        loss = self.criterion(logits, target, xyz, rgb)
        preds = torch.argmax(logits, dim=1).cpu().numpy().flatten()
        return loss.item(), preds

    def _eval_predict_candidates(self, feat, target):
        """Return per-file loss and predictions for all candidate points."""
        chunk_points = int(getattr(self.cfg, "DGCNN_EVAL_CHUNK_POINTS", 0) or 0)
        if (
            chunk_points <= 0
            or feat.shape[0] != 1
            or feat.shape[2] <= chunk_points
        ):
            loss_item, preds = self._eval_forward_once(feat, target)
            return loss_item, preds, False, 1

        n_points = int(feat.shape[2])
        pred_parts = []
        weighted_loss = 0.0
        total_weight = 0
        chunk_count = 0

        # All comparison backbones use the same deterministic 4096-candidate
        # evaluation chunks.  This covers every retained candidate while
        # matching the fixed training input budget and avoids giving selected
        # backbones a larger inference context.  Full-size chunks are batched;
        # the final short chunk is evaluated once without discarding points.
        full_chunk_starts = list(
            range(0, n_points - (n_points % chunk_points), chunk_points)
        )
        if full_chunk_starts:
            eval_batch_size = int(
                getattr(self.cfg, "STAGE2_BATCH_SIZE", 8)
            )
            for batch_start in range(0, len(full_chunk_starts), eval_batch_size):
                starts = full_chunk_starts[
                    batch_start:batch_start + eval_batch_size
                ]
                batch_feat = torch.cat(
                    [feat[:, :, start:start + chunk_points] for start in starts],
                    dim=0,
                )
                batch_target = torch.cat(
                    [target[:, start:start + chunk_points] for start in starts],
                    dim=0,
                )
                loss_item, batch_preds = self._eval_forward_once(
                    batch_feat, batch_target
                )
                weighted_loss += loss_item * len(starts) * chunk_points
                total_weight += len(starts) * chunk_points
                pred_parts.extend(
                    np.split(batch_preds, len(starts))
                )
                chunk_count += len(starts)
            next_start = len(full_chunk_starts) * chunk_points
        else:
            next_start = 0

        for start_idx in range(next_start, n_points, chunk_points):
            end_idx = min(start_idx + chunk_points, n_points)
            chunk_feat = feat[:, :, start_idx:end_idx]
            chunk_target = target[:, start_idx:end_idx]
            loss_item, chunk_preds = self._eval_forward_once(chunk_feat, chunk_target)
            weight = end_idx - start_idx
            weighted_loss += loss_item * weight
            total_weight += weight
            pred_parts.append(chunk_preds)
            chunk_count += 1
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        preds = np.concatenate(pred_parts, axis=0) if pred_parts else np.array([], dtype=np.int64)
        avg_loss = weighted_loss / max(total_weight, 1)
        return avg_loss, preds, True, chunk_count

    def _eval_forward_probabilities_once(self, feat, target):
        """Return foreground probabilities without applying an operating threshold."""
        feat = feat.to(self.cfg.DEVICE, non_blocking=True)
        target = target.to(self.cfg.DEVICE, non_blocking=True)
        xyz, rgb = feat[:, :3, :], feat[:, 3:6, :]
        outputs = self.model(feat)
        logits = outputs[0] if isinstance(outputs, tuple) else outputs
        loss = self.criterion(logits, target, xyz, rgb)
        probabilities = (
            F.softmax(logits, dim=1)[:, 1, :]
            .detach()
            .cpu()
            .numpy()
            .reshape(-1)
        )
        return loss.item(), probabilities

    def _eval_predict_candidate_probabilities(self, feat, target):
        """Return probabilities for every candidate using the locked chunk policy."""
        chunk_points = int(getattr(self.cfg, "DGCNN_EVAL_CHUNK_POINTS", 0) or 0)
        if (
            chunk_points <= 0
            or feat.shape[0] != 1
            or feat.shape[2] <= chunk_points
        ):
            loss_item, probabilities = self._eval_forward_probabilities_once(
                feat, target
            )
            return loss_item, probabilities, False, 1

        n_points = int(feat.shape[2])
        probability_parts = []
        weighted_loss = 0.0
        total_weight = 0
        chunk_count = 0
        full_chunk_starts = list(
            range(0, n_points - (n_points % chunk_points), chunk_points)
        )
        if full_chunk_starts:
            eval_batch_size = int(getattr(self.cfg, "STAGE2_BATCH_SIZE", 8))
            for batch_start in range(0, len(full_chunk_starts), eval_batch_size):
                starts = full_chunk_starts[
                    batch_start:batch_start + eval_batch_size
                ]
                batch_feat = torch.cat(
                    [feat[:, :, start:start + chunk_points] for start in starts],
                    dim=0,
                )
                batch_target = torch.cat(
                    [target[:, start:start + chunk_points] for start in starts],
                    dim=0,
                )
                loss_item, batch_probabilities = (
                    self._eval_forward_probabilities_once(batch_feat, batch_target)
                )
                weighted_loss += loss_item * len(starts) * chunk_points
                total_weight += len(starts) * chunk_points
                probability_parts.extend(
                    np.split(batch_probabilities, len(starts))
                )
                chunk_count += len(starts)
            next_start = len(full_chunk_starts) * chunk_points
        else:
            next_start = 0

        for start_idx in range(next_start, n_points, chunk_points):
            end_idx = min(start_idx + chunk_points, n_points)
            chunk_feat = feat[:, :, start_idx:end_idx]
            chunk_target = target[:, start_idx:end_idx]
            loss_item, chunk_probabilities = (
                self._eval_forward_probabilities_once(chunk_feat, chunk_target)
            )
            weight = end_idx - start_idx
            weighted_loss += loss_item * weight
            total_weight += weight
            probability_parts.append(chunk_probabilities)
            chunk_count += 1
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        probabilities = (
            np.concatenate(probability_parts, axis=0)
            if probability_parts
            else np.array([], dtype=np.float32)
        )
        avg_loss = weighted_loss / max(total_weight, 1)
        return avg_loss, probabilities, True, chunk_count

    def train_epoch(self, loader, epoch):
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        self.model.train()
        total_loss = 0
        all_preds, all_labels = [], []
        pbar = tqdm(loader, desc=f"Stage 2 {self.model_type} Epoch {epoch+1}")
        
        for feat, target, _ in pbar:
            feat, target = feat.to(self.cfg.DEVICE), target.to(self.cfg.DEVICE)
            xyz, rgb = feat[:, :3, :], feat[:, 3:6, :]

            self.optimizer.zero_grad(set_to_none=True)
            outputs = self.model(feat)
            logits = outputs[0] if isinstance(outputs, tuple) else outputs
            loss = self.criterion(logits, target, xyz, rgb)
            loss.backward()
            self.optimizer.step()
            
            total_loss += loss.item()
            preds = torch.argmax(logits, dim=1).cpu().numpy().flatten()
            all_preds.extend(preds)
            all_labels.extend(target.cpu().numpy().flatten())
            
        avg_loss = total_loss / len(loader)
        recall = recall_score(all_labels, all_preds, zero_division=0)
        precision = precision_score(all_labels, all_preds, zero_division=0)
        f1 = f1_score(all_labels, all_preds, zero_division=0)
        intersection = np.sum((np.array(all_preds) == 1) & (np.array(all_labels) == 1))
        union = np.sum((np.array(all_preds) == 1) | (np.array(all_labels) == 1))
        iou = intersection / union if union > 0 else 0.0
        
        self.logger.info(f"Train - Loss: {avg_loss:.4f}, Recall: {recall:.4f}, Precision: {precision:.4f}, IoU: {iou:.4f}, F1: {f1:.4f}")
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        return {"loss": avg_loss, "recall": recall, "precision": precision, "f1": f1, "iou": iou}

    def evaluate(self, loader, desc="Eval"):
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        self.model.eval()
        total_loss = 0.0
        all_preds, all_labels = [], []
        full_space_enabled = False
        full_space_files = 0
        candidate_space_files = 0
        eval_chunked_files = 0
        eval_chunk_count = 0

        with torch.no_grad():
            for feat, target, meta in tqdm(loader, desc=desc):
                loss_item, preds, chunked, chunk_count = self._eval_predict_candidates(feat, target)
                total_loss += loss_item
                if chunked:
                    eval_chunked_files += 1
                    eval_chunk_count += chunk_count

                use_full_space = (
                    isinstance(meta, dict)
                    and "has_full_space" in meta
                    and bool(meta["has_full_space"][0].item())
                    and feat.shape[0] == 1
                )
                if use_full_space:
                    full_space_enabled = True
                    full_space_files += 1
                    raw_num_points = int(meta["raw_num_points"][0].item())
                    raw_label = meta["raw_label"][0].cpu().numpy().astype(np.int64)
                    orig_index = meta["orig_index"][0].cpu().numpy().astype(np.int64)
                    if raw_label.size != raw_num_points:
                        raise RuntimeError(
                            f"{desc} raw-label length mismatch: "
                            f"{raw_label.size} != {raw_num_points}"
                        )
                    if len(preds) != len(orig_index):
                        raise RuntimeError(
                            f"{desc} candidate prediction/index mismatch: "
                            f"{len(preds)} != {len(orig_index)}"
                        )
                    if len(orig_index) and (
                        int(orig_index.min()) < 0
                        or int(orig_index.max()) >= raw_num_points
                    ):
                        raise RuntimeError(
                            f"{desc} orig_index lies outside the original ROI: "
                            f"range=[{int(orig_index.min())}, {int(orig_index.max())}], "
                            f"raw_num_points={raw_num_points}"
                        )
                    full_pred = np.zeros(raw_num_points, dtype=np.int64)
                    full_pred[orig_index] = preds
                    all_preds.extend(full_pred)
                    all_labels.extend(raw_label)
                else:
                    candidate_space_files += 1
                    all_preds.extend(preds)
                    all_labels.extend(target.cpu().numpy().flatten())

        all_preds, all_labels = np.array(all_preds), np.array(all_labels)
        if candidate_space_files:
            raise RuntimeError(
                f"{desc} received {candidate_space_files} file(s) without complete "
                "raw-label metadata. Formal validation and testing must compare "
                "predictions with raw_label after orig_index projection; candidate-"
                "space fallback is forbidden."
            )
        avg_loss = total_loss / len(loader)
        recall = recall_score(all_labels, all_preds, zero_division=0)
        precision = precision_score(all_labels, all_preds, zero_division=0)
        f1 = f1_score(all_labels, all_preds, zero_division=0)

        intersection = np.sum((all_preds == 1) & (all_labels == 1))
        union = np.sum((all_preds == 1) | (all_labels == 1))
        iou = intersection / union if union > 0 else 0

        metric_space = (
            "original_raw_roi_point_space"
            if full_space_enabled
            else "candidate_space"
        )
        if eval_chunked_files > 0:
            metric_space = f"{metric_space}_chunked_candidates"
        self.logger.info(f"{desc} [{metric_space}] - Loss: {avg_loss:.4f}, Recall: {recall:.4f}, Precision: {precision:.4f}, IoU: {iou:.4f}, F1: {f1:.4f}")
        if eval_chunked_files > 0:
            self.logger.info(
                f"{desc} {self.model_type} chunked full-candidate inference applied to {eval_chunked_files}/{len(loader)} files "
                f"({eval_chunk_count} chunks total, chunk points: {self.cfg.DGCNN_EVAL_CHUNK_POINTS})."
            )
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        return iou, {
            "loss": avg_loss,
            "recall": recall,
            "precision": precision,
            "f1": f1,
            "iou": iou,
            "metric_space": metric_space,
            "full_space_files": full_space_files,
            "candidate_space_files": candidate_space_files,
            "eval_chunked_files": eval_chunked_files,
            "eval_chunk_count": eval_chunk_count,
        }

    def save_history(self):
        os.makedirs(self.cfg.LOG_DIR, exist_ok=True)
        csv_path = os.path.join(self.cfg.LOG_DIR, f"epoch_metrics_{self.model_type}.csv")
        rows = [dict(zip(self.history.keys(), values)) for values in zip(*self.history.values())]
        if rows:
            with open(csv_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
                writer.writeheader()
                writer.writerows(rows)

        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt

            epochs = self.history["epoch"]
            fig, axes = plt.subplots(2, 2, figsize=(10, 7), dpi=150)
            panels = [
                ("loss", ["train_loss", "val_loss"]),
                ("iou", ["train_iou", "val_iou"]),
                ("f1", ["train_f1", "val_f1"]),
                ("recall/precision", ["val_recall", "val_precision"]),
            ]
            for ax, (title, keys) in zip(axes.ravel(), panels):
                for key in keys:
                    if key in self.history:
                        ax.plot(epochs, self.history[key], label=key)
                ax.set_title(title)
                ax.set_xlabel("epoch")
                ax.grid(True, alpha=0.3)
                ax.legend(fontsize=7)
            fig.suptitle(f"{self.model_type} training curves")
            fig.tight_layout()
            fig.savefig(os.path.join(self.cfg.LOG_DIR, f"epoch_curves_{self.model_type}.png"))
            plt.close(fig)
        except Exception as exc:
            self.logger.info(f"Curve PNG export skipped: {exc}")

    def record_epoch(self, epoch, lr, train_metrics, val_metrics=None, is_best=False):
        nan = float("nan")
        row = {
            "epoch": epoch,
            "lr": lr,
            "is_best": int(is_best),
            "train_loss": train_metrics["loss"],
            "train_recall": train_metrics["recall"],
            "train_precision": train_metrics["precision"],
            "train_iou": train_metrics["iou"],
            "train_f1": train_metrics["f1"],
            "val_loss": nan,
            "val_recall": nan,
            "val_precision": nan,
            "val_iou": nan,
            "val_f1": nan,
        }
        if val_metrics is not None:
            row.update({
                "val_loss": val_metrics["loss"],
                "val_recall": val_metrics["recall"],
                "val_precision": val_metrics["precision"],
                "val_iou": val_metrics["iou"],
                "val_f1": val_metrics["f1"],
            })
        for key, value in row.items():
            self.history[key].append(value)
        self.save_history()

    def run(self, train_loader, val_loader, test_loader):
        self.logger.info(f"Starting Stage 2 Training with {self.model_type}...")
        patience_counter = 0
        
        self.best_epoch = 0
        self.best_val_metrics = None
        self.best_test_metrics = None
        
        best_ckpt_path = os.path.join(self.cfg.MODEL_SAVE_DIR, f"best_stage2_{self.model_type}.pth")
        eval_every = max(1, int(getattr(self.cfg, "STAGE2_EVAL_EVERY", 1)))
        for epoch in range(self.cfg.STAGE2_EPOCHS):
            train_metrics = self.train_epoch(train_loader, epoch)
            should_eval = (epoch == 0) or ((epoch + 1) % eval_every == 0) or (epoch + 1 == self.cfg.STAGE2_EPOCHS)
            val_metrics = None
            is_best = False

            if should_eval:
                val_iou, val_metrics = self.evaluate(val_loader, "Val")
                if val_iou > self.best_iou:
                    is_best = True
                    self.best_iou = val_iou
                    self.best_epoch = epoch + 1
                    self.best_val_metrics = val_metrics
                    torch.save(self.model.state_dict(), best_ckpt_path)
                    self.logger.info(f">>> Best Model Saved (Val IoU: {val_iou:.4f})")
                    patience_counter = 0
                else:
                    patience_counter += 1
                    self.logger.info(f"Patience counter: {patience_counter}/{self.cfg.STAGE2_PATIENCE}")
            else:
                self.logger.info(f"Validation skipped at epoch {epoch+1} (eval_every={eval_every})")

            self.scheduler.step()
            curr_lr = self.optimizer.param_groups[0]['lr']
            self.logger.info(f"Epoch {epoch+1} LR: {curr_lr:.6f}")
            self.record_epoch(epoch + 1, curr_lr, train_metrics, val_metrics, is_best=is_best)

            if should_eval and patience_counter >= self.cfg.STAGE2_PATIENCE:
                self.logger.info(f"Early stopping triggered at epoch {epoch+1}")
                break

        if (
            self.best_val_metrics is not None
            and os.path.exists(best_ckpt_path)
            and not bool(getattr(self.cfg, "DEFER_REAL_EVALUATION", False))
        ):
            self.model.load_state_dict(torch.load(best_ckpt_path, map_location=self.cfg.DEVICE))
            _, self.best_test_metrics = self.evaluate(test_loader, "Test")
            self.logger.info(
                f">>> Final Test Evaluated Once from Best-Val Checkpoint "
                f"(Epoch {self.best_epoch}, Val IoU: {self.best_iou:.4f}, "
                f"Test IoU: {self.best_test_metrics['iou']:.4f})"
            )
        
        print("\n" + "="*60)
        print(f"*** Stage 2 {self.model_type.upper()} BEST MODEL SUMMARY (Epoch {self.best_epoch}) ***")
        print("="*60)
        if self.best_val_metrics:
            print(f"[Val Dataset]   Recall: {self.best_val_metrics['recall']:.4f}, IoU: {self.best_val_metrics['iou']:.4f}")
        if self.best_test_metrics:
            print(f"[Test Dataset]  Recall: {self.best_test_metrics['recall']:.4f}, IoU: {self.best_test_metrics['iou']:.4f}")
        print("="*60 + "\n")
        
        return self.best_val_metrics, self.best_test_metrics

# ============================================
# ============================================
def main():
    args = parse_args()
    config = Config()
    config.MODE = args.mode
    Config.STAGE2_OPTIMIZER = str(args.optimizer).lower()
    Config.DEFER_REAL_EVALUATION = bool(args.defer_real_evaluation)
    Config.STAGE2_OFFLINE_ROOT = os.path.abspath(args.offline_root)
    Config.RESULTS_ROOT = os.path.abspath(args.results_root)
    config.OVERWRITE = bool(args.overwrite)
    if args.num_workers is not None:
        config.NUM_WORKERS = args.num_workers
    Config.RUN_TAG = args.run_tag
    if args.model and args.model != "all":
        config.STAGE2_MODEL_TYPES = [args.model]
        Config.RUN_MODEL_TAG = args.model
    elif args.model == "all":
        config.STAGE2_MODEL_TYPES = [
            'pointnet', 'pointnet2', 'pointmlp', 'dgcnn', 'pointtransformer',
            'pointnext', 'curvenet',
        ]
        Config.RUN_MODEL_TAG = None
    
    modes_to_process = [config.MODE]

    global_ablation_results = {}

    for current_mode in modes_to_process:
        config.update_mode(current_mode)
        print("\n" + "#"*60)
        print(f"### RUNNING ABLATION MODE: {current_mode.upper()} ###")
        print("#"*60 + "\n")
        
        # ==========================================================
        def prepare_directory(path, desc, clean=False):
            if os.path.exists(path) and os.listdir(path):
                if not clean:
                    raise FileExistsError(
                        f"Existing {desc} directory is protected: {path}. "
                        "Pass --overwrite only when replacement is intended."
                    )
                print(f">>> Replacing existing {desc} directory: {path}")
                shutil.rmtree(path)
            os.makedirs(path, exist_ok=True)

        if config.RUN_STAGE == 2:
            prepare_directory(config.OUTPUT_ROOT, f"Results ({current_mode})", clean=config.OVERWRITE)
            for sub in [config.MODEL_SAVE_DIR, config.VIZ_DIR, config.LOG_DIR]:
                os.makedirs(sub, exist_ok=True)

        # ==========================================================
        # ==========================================================
        all_summary_results = {}
        if config.RUN_STAGE == 2:
            print("\n" + "="*50)
            print(f">>> [Stage 2] Starting Fine Segmentation Ablation: {current_mode}")
            print("="*50)
            
            # Build synthetic train/validation and real test datasets.
            train_ds = Stage2Dataset(config.STAGE2_OFFLINE_DIR, split="train", augment=config.STAGE2_USE_ONLINE_AUGMENT)
            val_ds = Stage2Dataset(config.STAGE2_OFFLINE_DIR, split="val", augment=False)
            test_ds = Stage2Dataset(config.STAGE2_OFFLINE_DIR, split="test", augment=False)
            validate_formal_protocol(config, train_ds, val_ds, test_ds)
            dataset_summary_path = os.path.join(config.OUTPUT_ROOT, "dataset_input_summary.json")
            with open(dataset_summary_path, "w", encoding="utf-8") as f:
                json.dump(
                    {
                        "mode": current_mode,
                        "requested_models": config.STAGE2_MODEL_TYPES,
                        "run_tag": config.RUN_TAG,
                        "run_config": {
                            "epochs": config.STAGE2_EPOCHS,
                            "batch_size": config.STAGE2_BATCH_SIZE,
                            "model_batch_size_overrides": config.STAGE2_MODEL_BATCH_SIZE_OVERRIDES,
                            "dgcnn_eval_strategy": config.DGCNN_EVAL_STRATEGY,
                            "dgcnn_eval_chunk_points": config.DGCNN_EVAL_CHUNK_POINTS,
                            "sample_points": config.STAGE2_SAMPLE_POINTS,
                            "patience": config.STAGE2_PATIENCE,
                            "eval_every": config.STAGE2_EVAL_EVERY,
                            "num_workers": config.NUM_WORKERS,
                            "input_channels": config.STAGE2_INPUT_CHANNELS,
                            "augment_mode": config.STAGE2_AUG_MODE,
                            "device": str(config.DEVICE),
                            "seed": config.SEED,
                            "optimizer": config.STAGE2_OPTIMIZER,
                            "defer_real_evaluation": bool(config.DEFER_REAL_EVALUATION),
                            "model_configs": {m: config.STAGE2_MODEL_CONFIGS[m] for m in config.STAGE2_MODEL_TYPES},
                        },
                        "feature_protocol": {
                            "stage2_input": "XYZRGB only",
                            "input_columns": ["X", "Y", "Z", "R", "G", "B"],
                            "label_column": "last column in the LCC cache",
                            "note": (
                                "LCC offline caches may retain additional audit descriptors, "
                                "but they are not used as model inputs in this benchmark."
                            ),
                        },
                        "split_protocol": {
                            "policy": config.STAGE2_SPLIT_POLICY,
                            "holdout_styles": list(config.STAGE2_HOLDOUT_STYLES),
                            "formal_pure_sim2real": config.STAGE2_SPLIT_POLICY == "synthetic_style_holdout",
                            "description": (
                                "Formal pure Sim2Real uses synthetic shoe-design-level validation "
                                "and reserves all real scans exclusively for final testing."
                            ),
                        },
                        "train": train_ds.summary(),
                        "val": val_ds.summary(),
                        "test": test_ds.summary(),
                        "empty_candidate_note": (
                            "Training samples with zero LCC candidates are skipped because the baseline model has no point-wise input. "
                            "Validation/test samples are retained; zero-candidate cases are evaluated as all-background predictions in full point-cloud space."
                        ),
                    },
                    f,
                    indent=2,
                )
            
            if len(train_ds) == 0:
                print(f"Error: No training data found for {current_mode}. Please run 02_generate_lcc_candidates.py first.")
                if config.MODE != 'all': return
                else: continue

            if args.dry_run:
                for model_name in config.STAGE2_MODEL_TYPES:
                    trainer = Stage2Trainer(config, current_model_type=model_name)
                    parameter_count = sum(
                        parameter.numel() for parameter in trainer.model.parameters()
                    )
                    print(
                        f">>> Dry run passed: model={model_name}, "
                        f"optimizer={config.STAGE2_OPTIMIZER}, "
                        f"parameters={parameter_count}"
                    )
                return

            for model_name in config.STAGE2_MODEL_TYPES:
                train_batch_size = int(
                    config.STAGE2_MODEL_BATCH_SIZE_OVERRIDES.get(model_name.lower(), config.STAGE2_BATCH_SIZE)
                )
                train_loader = make_loader(train_ds, train_batch_size, shuffle=True)
                # Full-space graph-model evaluation performs many sequential
                # chunks per sample.  On Windows, persistent validation/test
                # workers can deadlock after several epochs.  Loading these
                # two read-only splits in the parent process changes neither
                # samples nor metrics, while training retains the configured
                # worker count.
                val_loader = make_loader(val_ds, 1, shuffle=False, num_workers=0)
                test_loader = make_loader(test_ds, 1, shuffle=False, num_workers=0)
                print(f"\n" + "-"*60)
                print(f"[Stage2] Dataset Variant: {current_mode} | Backbone: {model_name} | Aug Mode: {config.STAGE2_AUG_MODE}")
                print(
                    f"[Stage2] Batch size: {train_batch_size} | Eval batch: 1 "
                    f"| Sample points: {config.STAGE2_SAMPLE_POINTS}"
                )
                print("-"*60)
                try:
                    trainer = Stage2Trainer(config, current_model_type=model_name)
                    s2_val, s2_test = trainer.run(train_loader, val_loader, test_loader)
                    
                    all_summary_results[model_name] = {'val': s2_val, 'test': s2_test}
                except Exception as e:
                    print(f"!!! Error training {model_name}: {e}")
                    continue

            print(f"\n>>> All Stage 2 tasks for {current_mode} have been completed.")
            
            import copy
            global_ablation_results[current_mode] = copy.deepcopy(all_summary_results)
        
        # ==========================================================
        if all_summary_results:
            summary_path = os.path.join(config.OUTPUT_ROOT, "final_ablation_summary.txt")
            with open(summary_path, "w", encoding="utf-8") as f:
                f.write("="*60 + "\n")
                f.write("       ABLATION STUDY SUMMARY REPORT (DATASET VARIANT)\n")
                f.write("="*60 + "\n")
                f.write(f"Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Ablation Version: {current_mode}\n")
                f.write("-" * 60 + "\n\n")
                
                for m_name, results in all_summary_results.items():
                    f.write(f"BACKBONE: {m_name.upper()}\n")
                    if results['val']:
                        v = results['val']
                        f.write(f"  [Validation/{v.get('metric_space', 'unknown')}] IoU: {v['iou']:.4f}, F1: {v['f1']:.4f}, Recall: {v['recall']:.4f}, Precision: {v['precision']:.4f}\n")
                    if results['test']:
                        t = results['test']
                        f.write(f"  [Test - Real/{t.get('metric_space', 'unknown')}]       IoU: {t['iou']:.4f}, F1: {t['f1']:.4f}, Recall: {t['recall']:.4f}, Precision: {t['precision']:.4f}\n")
                    f.write("-" * 30 + "\n")
            
            print("\n" + "*"*60)
            print(f">>> Ablation evaluation summary for {current_mode} saved to:\n{os.path.abspath(summary_path)}")
            print("*"*60 + "\n")

    # ==========================================================
    if len(modes_to_process) > 1 and global_ablation_results:
        global_summary_path = os.path.join(PROJECT_ROOT, "experiments", "ablation_results", "global_ablation_summary.txt")
        with open(global_summary_path, "w", encoding="utf-8") as f:
            f.write("="*80 + "\n")
            f.write("             GLOBAL ABLATION STUDY CROSS-MODE SUMMARY REPORT\n")
            f.write("="*80 + "\n")
            f.write(f"Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Ablation Versions Run: {', '.join(modes_to_process)}\n")
            f.write("-" * 80 + "\n\n")
            
            for mode_name, mode_res in global_ablation_results.items():
                f.write(f"### ABLATION VARIANT: {mode_name.upper()} ###\n")
                for m_name, results in mode_res.items():
                    f.write(f"  BACKBONE: {m_name.upper()}\n")
                    if results['test']:
                        t = results['test']
                        f.write(f"    [Test Results - Real/{t.get('metric_space', 'unknown')}] IoU: {t['iou']:.4f}, F1: {t['f1']:.4f}, Recall: {t['recall']:.4f}, Precision: {t['precision']:.4f}\n")
                f.write("\n" + "-" * 40 + "\n\n")
        
        print("\n" + "#"*60)
        print(f">>> GLOBAL Ablation summary saved to:\n{os.path.abspath(global_summary_path)}")
        print("#"*60 + "\n")

    if config.RUN_STAGE != 2:
        print(f"Invalid RUN_STAGE: {config.RUN_STAGE}. Only Stage 2 training is supported in this script.")
    else:
        print("\n" + "="*50)
        print(">>> All requested Ablation Pipeline tasks completed.")
        print("="*50)

if __name__ == "__main__":
    main()

